FROM openjdk:8-jdk-alpine
MAINTAINER test.com
RUN addgroup -S spring && adduser-S spring -G spring
USER psring:spring
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} Backend-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/Backend-0.0.1-SNAPSHOT.jar"]